# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Burnguard < Formula
  desc "Stop surprise AI API bills before they happen"
  homepage "https://burnguard.run"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Verifieddanny/BurnGuard/releases/download/v0.1.0/burnguard_darwin_amd64.tar.gz"
      sha256 "0c0deebc23e8269477db8d8535b7430d2417adce78b9c565f7e091a501f6f19e"

      define_method(:install) do
        bin.install "burnguard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Verifieddanny/BurnGuard/releases/download/v0.1.0/burnguard_darwin_arm64.tar.gz"
      sha256 "fe25ecb6c5d95e37010daeb316e6fb1e4083301a28f642046dff3491c8994a3a"

      define_method(:install) do
        bin.install "burnguard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Verifieddanny/BurnGuard/releases/download/v0.1.0/burnguard_linux_amd64.tar.gz"
      sha256 "25260b411a3f66ac940ca57767b8b2465c7bed86c129bc5581e7a547014c2ace"
      define_method(:install) do
        bin.install "burnguard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Verifieddanny/BurnGuard/releases/download/v0.1.0/burnguard_linux_arm64.tar.gz"
      sha256 "d69a585986beb0e4be874bf9bf69f42964aac3ea14695c93316d3f8153434102"
      define_method(:install) do
        bin.install "burnguard"
      end
    end
  end
end
