# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Burnguard < Formula
  desc "Stop surprise AI API bills before they happen"
  homepage "https://burnguard.run"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Verifieddanny/BurnGuard/releases/download/v0.1.1/burnguard_darwin_amd64.tar.gz"
      sha256 "aef705f974dc96cfd0f8d67474ef4a4f00b7923b13925d2c27df46b9daeaa07d"

      define_method(:install) do
        bin.install "burnguard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Verifieddanny/BurnGuard/releases/download/v0.1.1/burnguard_darwin_arm64.tar.gz"
      sha256 "ec1463f17dd24d437f50b62c3a26c401fd33057d5f9e16b4d2c5d1fcd24b80fb"

      define_method(:install) do
        bin.install "burnguard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Verifieddanny/BurnGuard/releases/download/v0.1.1/burnguard_linux_amd64.tar.gz"
      sha256 "581fea4a8c7284e8a70771823daa535cb8028977177cb7f6080064fb4dea09c4"
      define_method(:install) do
        bin.install "burnguard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Verifieddanny/BurnGuard/releases/download/v0.1.1/burnguard_linux_arm64.tar.gz"
      sha256 "f53391b0f8119555c46e59f67a7ea04be20718d2c016bc71e19bdffcbdce23e1"
      define_method(:install) do
        bin.install "burnguard"
      end
    end
  end
end
